---
configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
 - Launchpad
 - TV
 - Podcasts
 - 'App Store'
dockitems_persist: []
  - ghostty

configure_sudoers: true
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/aram535/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_repo_version: master # Replace with your default branch
dotfiles_files:
    - .bash_profile
    - .bashrc
    - .gitignore
    - .inputrc
    - .osx
    - .vimrc

homebrew_installed_packages:
    # - ansible # Installed via Pip.
    - ansible
    - autoconf
    - awscli
    - bash
    - bash-completion
    - bat
    - ca-certificates
    - certifi
    - chromedriver
    - cowsay
    - cryptography
    - curl
    - docker
    - docutils
    - dropbox
    - eza
    - ffmpeg
    - firefox
    - fontconfig
    - fortune
    - freetype
    - fzf
    - gettext
    - gh
    - git
    - google-chrome
    - go
    - gnu-sed
    - gpg
    - hashicorp/tap/vault
    - htop
    - httpie
    - iperf
    - jq
    - moreutils
    - ncurses
    - nmap
    - openjdk
    - openssl
    - openssl@3
    - pkg-config
    - pngpaste
    - pv
    - readline
    - ripgrep
    - shellcheck
    - slack
    - ssh-copy-id
    - starship
    - tflint
    - watch
    - wget
    - yamllint
    - yt-dlp

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
    - ghostty
    - iterm2
    - nerd-fonts
    - nerd-fonts-fira-code
    - postman
    - visual-studio-code
    - vlc
    - bitwarden
    - rectagle
    - alfred

osx_script: '~/.osx --no-restart'

# Set to 'true' to configure Sublime Text.
configure_sublime: false

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
